# Generated by Django 2.1.3 on 2018-11-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('ie_code', models.IntegerField(choices=[(1, 'Export'), (2, 'Import')])),
                ('coa_code', models.IntegerField()),
                ('coa_name', models.CharField(max_length=50)),
                ('ccc_code', models.IntegerField()),
                ('ccc_name', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=2)),
                ('country_name', models.CharField(max_length=50)),
                ('weight', models.IntegerField()),
                ('usd', models.IntegerField()),
                ('twd', models.IntegerField()),
            ],
        ),
    ]
