# Generated by Django 2.1.3 on 2018-12-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='twd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='usd',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
